### ISSUE TITLE
AttributeError: 'super' object has no attribute 'conv2d_forward'

### ISSUE THREAD

**Issue by Li-by** [joe-siyuan-qiao/DetectoRS#5]
when inferece image:
raceback (most recent call last):
  File "tools/demo.py", line 101, in <module>
    result = inference_detector(model, img_path)
  File "/mnt/mmdet/apis/inference.py", line 86, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/root/miniconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/mnt/mmdet/models/detectors/base.py", line 149, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/mnt/mmdet/models/detectors/base.py", line 130, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/mnt/mmdet/models/detectors/htc.py", line 311, in simple_test
    x = self.extract_feat(img)
  File "/mnt/mmdet/models/detectors/rfp.py", line 98, in extract_feat
    x = self.backbone(img)
  File "/root/miniconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/mmdet/models/backbones/resnet.py", line 583, in forward
    x = self.conv1(x)
  File "/root/miniconda3/envs/mmdetection/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/mmdet/ops/conv_ws.py", line 84, in forward
    return super().conv2d_forward(x, weight)
AttributeError: 'super' object has no attribute 'conv2d_forward'

**Comment by joe-siyuan-qiao** [comment]
Thanks for reporting this!

This seems to be a PyTorch version problem. PyTorch 1.5 has changed its internal API. Here's the environment we use:

pytorch==1.4.0
torchvision=0.5.0
cudatoolkit=10.1.243

I'll also add this to README so other people won't have to deal with this issue. Thanks again.

**Comment by pengxiaoxiao** [comment]
are you sure? conv2d has no conv2d_forward func!

**Comment by joe-siyuan-qiao** [comment]
@pengxiaoxiao PyTorch used to have it:

https://github.com/pytorch/pytorch/blob/v1.4.0/torch/nn/modules/conv.py#L334

**Comment by unlabeledData** [comment]
I think `super().forward(x)` can replace the `conv2d_forward` here.
Then the code works with pytorch 1.1.0 to 1.1.4.
Right? Not very sure.

**Comment by sailfish009** [comment]
> @pengxiaoxiao PyTorch used to have it:
> 
> https://github.com/pytorch/pytorch/blob/v1.4.0/torch/nn/modules/conv.py#L334

function name changed in latest pytorch v1.7.0x version, 

`super()._conv_forward(...) `
